name: Tech Debt
description: Refactor or redesign something that works but is fragile/ugly
title: "debt: "
labels: ["type:tech-debt"]
body:
  - type: textarea
    id: pain
    attributes:
      label: The pain
      description: What’s currently wrong (fragile, hard to change, slow, confusing)?
      placeholder: "Input handling is duplicated across scripts and causes inconsistent behavior."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed fix
      description: What change would pay down the debt?
      placeholder: "Create an InputService and migrate all input reads to it."
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      placeholder: |
        - [ ] Old approach removed or isolated
        - [ ] New approach documented
        - [ ] No regressions in Play Mode
        - [ ] No new Console errors
        - [ ] Committed + pushed
    validations:
      required: true

  - type: dropdown
    id: system
    attributes:
      label: System (apply matching sys:* label)
      options:
        - sys:procgen
        - sys:simulation
        - sys:events
        - sys:save-load
        - sys:ui
        - sys:build-ci
        - sys:audio
        - sys:perf
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (apply p0/p1/p2 label)
      options:
        - p0 (blocks progress / crash / data loss)
        - p1 (important, next few sessions)
        - p2 (nice-to-have / later)
    validations:
      required: true
